import type { Metadata } from "next";
import "./globals.css";
import CoinLogo from "@assets/images/coin.png";
import Providers from "./components/Providers";
import GoogleSignInButton from "./components/SignInButton";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="font-DOS">
        <Providers>
        <nav className="flex gap-4 px-4 py-2 items-center justify-between">
          <a href="/"><Image src={CoinLogo} width={32} alt="coin_logo"/></a>
          <div></div>
          <GoogleSignInButton />
        </nav>
        {children}
        </Providers>
      </body>
    </html>
  );
}
